package shared

type CodatAssessDataContractsCashFlowTransactionsTransactionsDataSource struct {
	Transactions []CodatAssessDataContractsCashFlowTransactionsCashFlowReportBankingTransaction `json:"transactions,omitempty"`
}
