package shared

type CodatDataContractsDatasetsBankingTransactionCategoryStatusEnum string

const (
	CodatDataContractsDatasetsBankingTransactionCategoryStatusEnumUnknown  CodatDataContractsDatasetsBankingTransactionCategoryStatusEnum = "Unknown"
	CodatDataContractsDatasetsBankingTransactionCategoryStatusEnumActive   CodatDataContractsDatasetsBankingTransactionCategoryStatusEnum = "Active"
	CodatDataContractsDatasetsBankingTransactionCategoryStatusEnumArchived CodatDataContractsDatasetsBankingTransactionCategoryStatusEnum = "Archived"
)
