package shared

type CodatDataContractsDatasetsPaymentMethodStatusEnum string

const (
	CodatDataContractsDatasetsPaymentMethodStatusEnumUnknown  CodatDataContractsDatasetsPaymentMethodStatusEnum = "Unknown"
	CodatDataContractsDatasetsPaymentMethodStatusEnumActive   CodatDataContractsDatasetsPaymentMethodStatusEnum = "Active"
	CodatDataContractsDatasetsPaymentMethodStatusEnumArchived CodatDataContractsDatasetsPaymentMethodStatusEnum = "Archived"
)
