package shared

type CodatDataContractsDatasetsBankingAccountTypeEnum string

const (
	CodatDataContractsDatasetsBankingAccountTypeEnumUnknown CodatDataContractsDatasetsBankingAccountTypeEnum = "Unknown"
	CodatDataContractsDatasetsBankingAccountTypeEnumCredit  CodatDataContractsDatasetsBankingAccountTypeEnum = "Credit"
	CodatDataContractsDatasetsBankingAccountTypeEnumDebit   CodatDataContractsDatasetsBankingAccountTypeEnum = "Debit"
)
