package shared

type CodatDataContractsDatasetsCashFlowStatementReportingDataEnum string

const (
	CodatDataContractsDatasetsCashFlowStatementReportingDataEnumUnknown  CodatDataContractsDatasetsCashFlowStatementReportingDataEnum = "Unknown"
	CodatDataContractsDatasetsCashFlowStatementReportingDataEnumIndirect CodatDataContractsDatasetsCashFlowStatementReportingDataEnum = "Indirect"
	CodatDataContractsDatasetsCashFlowStatementReportingDataEnumDirect   CodatDataContractsDatasetsCashFlowStatementReportingDataEnum = "Direct"
)
