package shared

type CodatAssessDataContractsFinancialsMetricsMetricPeriodUnitEnum string

const (
	CodatAssessDataContractsFinancialsMetricsMetricPeriodUnitEnumMonth CodatAssessDataContractsFinancialsMetricsMetricPeriodUnitEnum = "Month"
	CodatAssessDataContractsFinancialsMetricsMetricPeriodUnitEnumWeek  CodatAssessDataContractsFinancialsMetricsMetricPeriodUnitEnum = "Week"
	CodatAssessDataContractsFinancialsMetricsMetricPeriodUnitEnumDay   CodatAssessDataContractsFinancialsMetricsMetricPeriodUnitEnum = "Day"
)
