package shared

type CodatDataContractsDatasetsCashFlowStatementReportingBasisEnum string

const (
	CodatDataContractsDatasetsCashFlowStatementReportingBasisEnumUnknown CodatDataContractsDatasetsCashFlowStatementReportingBasisEnum = "Unknown"
	CodatDataContractsDatasetsCashFlowStatementReportingBasisEnumAccrual CodatDataContractsDatasetsCashFlowStatementReportingBasisEnum = "Accrual"
	CodatDataContractsDatasetsCashFlowStatementReportingBasisEnumCash    CodatDataContractsDatasetsCashFlowStatementReportingBasisEnum = "Cash"
)
