package shared

type CodatAssessDataContractsFinancialsStatementsAccountCategoryStatusEnum string

const (
	CodatAssessDataContractsFinancialsStatementsAccountCategoryStatusEnumConfirmed CodatAssessDataContractsFinancialsStatementsAccountCategoryStatusEnum = "Confirmed"
	CodatAssessDataContractsFinancialsStatementsAccountCategoryStatusEnumSuggested CodatAssessDataContractsFinancialsStatementsAccountCategoryStatusEnum = "Suggested"
)
