package shared

type CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnum string

const (
	CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnumUnknown        CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnum = "Unknown"
	CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnumSandboxOnly    CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnum = "SandboxOnly"
	CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnumLiveOnly       CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnum = "LiveOnly"
	CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnumLiveAndSandbox CodatPublicAPIModelsPlatformCredentialsIntegrationSupportedEnvironmentsEnum = "LiveAndSandbox"
)
