package shared

type CodatDataContractsDatasetsCustomerStatusEnum string

const (
	CodatDataContractsDatasetsCustomerStatusEnumUnknown  CodatDataContractsDatasetsCustomerStatusEnum = "Unknown"
	CodatDataContractsDatasetsCustomerStatusEnumActive   CodatDataContractsDatasetsCustomerStatusEnum = "Active"
	CodatDataContractsDatasetsCustomerStatusEnumArchived CodatDataContractsDatasetsCustomerStatusEnum = "Archived"
)
