package shared

type CodatDataContractsDatasetsAddressTypeEnum string

const (
	CodatDataContractsDatasetsAddressTypeEnumUnknown  CodatDataContractsDatasetsAddressTypeEnum = "Unknown"
	CodatDataContractsDatasetsAddressTypeEnumBilling  CodatDataContractsDatasetsAddressTypeEnum = "Billing"
	CodatDataContractsDatasetsAddressTypeEnumDelivery CodatDataContractsDatasetsAddressTypeEnum = "Delivery"
)
