package shared

type CodatAssessDataContractsFinancialsMetricsMetricUnitEnum string

const (
	CodatAssessDataContractsFinancialsMetricsMetricUnitEnumRatio CodatAssessDataContractsFinancialsMetricsMetricUnitEnum = "Ratio"
	CodatAssessDataContractsFinancialsMetricsMetricUnitEnumMoney CodatAssessDataContractsFinancialsMetricsMetricUnitEnum = "Money"
)
