package shared

type CodatDataContractsDatasetsAccountsReceivableIsBilledToTypeEnum string

const (
	CodatDataContractsDatasetsAccountsReceivableIsBilledToTypeEnumUnknown       CodatDataContractsDatasetsAccountsReceivableIsBilledToTypeEnum = "Unknown"
	CodatDataContractsDatasetsAccountsReceivableIsBilledToTypeEnumNotApplicable CodatDataContractsDatasetsAccountsReceivableIsBilledToTypeEnum = "NotApplicable"
	CodatDataContractsDatasetsAccountsReceivableIsBilledToTypeEnumProject       CodatDataContractsDatasetsAccountsReceivableIsBilledToTypeEnum = "Project"
)
