package shared

type CodatDataContractsDatasetsPurchaseOrderStatusEnum string

const (
	CodatDataContractsDatasetsPurchaseOrderStatusEnumUnknown CodatDataContractsDatasetsPurchaseOrderStatusEnum = "Unknown"
	CodatDataContractsDatasetsPurchaseOrderStatusEnumDraft   CodatDataContractsDatasetsPurchaseOrderStatusEnum = "Draft"
	CodatDataContractsDatasetsPurchaseOrderStatusEnumOpen    CodatDataContractsDatasetsPurchaseOrderStatusEnum = "Open"
	CodatDataContractsDatasetsPurchaseOrderStatusEnumClosed  CodatDataContractsDatasetsPurchaseOrderStatusEnum = "Closed"
	CodatDataContractsDatasetsPurchaseOrderStatusEnumVoid    CodatDataContractsDatasetsPurchaseOrderStatusEnum = "Void"
)
