package shared

type CodatDataContractsDatasetsProfitAndLossReportingTypeEnum string

const (
	CodatDataContractsDatasetsProfitAndLossReportingTypeEnumUnknown CodatDataContractsDatasetsProfitAndLossReportingTypeEnum = "Unknown"
	CodatDataContractsDatasetsProfitAndLossReportingTypeEnumAccrual CodatDataContractsDatasetsProfitAndLossReportingTypeEnum = "Accrual"
	CodatDataContractsDatasetsProfitAndLossReportingTypeEnumCash    CodatDataContractsDatasetsProfitAndLossReportingTypeEnum = "Cash"
)
