package shared

type CodatDataContractsDatasetsJournalStatusEnum string

const (
	CodatDataContractsDatasetsJournalStatusEnumUnknown  CodatDataContractsDatasetsJournalStatusEnum = "Unknown"
	CodatDataContractsDatasetsJournalStatusEnumActive   CodatDataContractsDatasetsJournalStatusEnum = "Active"
	CodatDataContractsDatasetsJournalStatusEnumArchived CodatDataContractsDatasetsJournalStatusEnum = "Archived"
)
