package shared

type CodatDataContractsDatasetsBankAccountTypeEnum string

const (
	CodatDataContractsDatasetsBankAccountTypeEnumUnknown CodatDataContractsDatasetsBankAccountTypeEnum = "Unknown"
	CodatDataContractsDatasetsBankAccountTypeEnumCredit  CodatDataContractsDatasetsBankAccountTypeEnum = "Credit"
	CodatDataContractsDatasetsBankAccountTypeEnumDebit   CodatDataContractsDatasetsBankAccountTypeEnum = "Debit"
)
