package shared

type CodatAssessDataContractsCashFlowTransactionsSourceTypeEnum string

const (
	CodatAssessDataContractsCashFlowTransactionsSourceTypeEnumBanking CodatAssessDataContractsCashFlowTransactionsSourceTypeEnum = "Banking"
)
