package shared

type CodatAssessDataContractsFinancialsMetricsMetricErrorTypeEnum string

const (
	CodatAssessDataContractsFinancialsMetricsMetricErrorTypeEnumUncategorizedAccounts CodatAssessDataContractsFinancialsMetricsMetricErrorTypeEnum = "UncategorizedAccounts"
	CodatAssessDataContractsFinancialsMetricsMetricErrorTypeEnumMissingInputData      CodatAssessDataContractsFinancialsMetricsMetricErrorTypeEnum = "MissingInputData"
	CodatAssessDataContractsFinancialsMetricsMetricErrorTypeEnumInputDataError        CodatAssessDataContractsFinancialsMetricsMetricErrorTypeEnum = "InputDataError"
)
