package shared

type CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorTypeEnum string

const (
	CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorTypeEnumMissingAccountData CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorTypeEnum = "MissingAccountData"
	CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorTypeEnumDatesOutOfRange    CodatAssessDataContractsFinancialsMetricsMetricPeriodErrorTypeEnum = "DatesOutOfRange"
)
