package shared

type CodatPublicAPIModelsPlatformCredentialsDataProvidedByEnum string

const (
	CodatPublicAPIModelsPlatformCredentialsDataProvidedByEnumUnknown CodatPublicAPIModelsPlatformCredentialsDataProvidedByEnum = "Unknown"
	CodatPublicAPIModelsPlatformCredentialsDataProvidedByEnumCodat   CodatPublicAPIModelsPlatformCredentialsDataProvidedByEnum = "Codat"
	CodatPublicAPIModelsPlatformCredentialsDataProvidedByEnumClient  CodatPublicAPIModelsPlatformCredentialsDataProvidedByEnum = "Client"
)
