package shared

type CodatDataContractsPushPushChangeTypeEnum string

const (
	CodatDataContractsPushPushChangeTypeEnumUnknown  CodatDataContractsPushPushChangeTypeEnum = "Unknown"
	CodatDataContractsPushPushChangeTypeEnumCreated  CodatDataContractsPushPushChangeTypeEnum = "Created"
	CodatDataContractsPushPushChangeTypeEnumModified CodatDataContractsPushPushChangeTypeEnum = "Modified"
	CodatDataContractsPushPushChangeTypeEnumDeleted  CodatDataContractsPushPushChangeTypeEnum = "Deleted"
)
