package shared

type CodatDataContractsDatasetsCommerceProductStatusEnum string

const (
	CodatDataContractsDatasetsCommerceProductStatusEnumUnknown     CodatDataContractsDatasetsCommerceProductStatusEnum = "Unknown"
	CodatDataContractsDatasetsCommerceProductStatusEnumPublished   CodatDataContractsDatasetsCommerceProductStatusEnum = "Published"
	CodatDataContractsDatasetsCommerceProductStatusEnumUnpublished CodatDataContractsDatasetsCommerceProductStatusEnum = "Unpublished"
)
