package shared

type CodatStandardReportingContractsReportErrorTypeEnum string

const (
	CodatStandardReportingContractsReportErrorTypeEnumDatesOutOfRange       CodatStandardReportingContractsReportErrorTypeEnum = "DatesOutOfRange"
	CodatStandardReportingContractsReportErrorTypeEnumDataNotSynced         CodatStandardReportingContractsReportErrorTypeEnum = "DataNotSynced"
	CodatStandardReportingContractsReportErrorTypeEnumDataSetNotSupported   CodatStandardReportingContractsReportErrorTypeEnum = "DataSetNotSupported"
	CodatStandardReportingContractsReportErrorTypeEnumDataSyncFailed        CodatStandardReportingContractsReportErrorTypeEnum = "DataSyncFailed"
	CodatStandardReportingContractsReportErrorTypeEnumDataTypeNotEnabled    CodatStandardReportingContractsReportErrorTypeEnum = "DataTypeNotEnabled"
	CodatStandardReportingContractsReportErrorTypeEnumUncategorizedAccounts CodatStandardReportingContractsReportErrorTypeEnum = "UncategorizedAccounts"
	CodatStandardReportingContractsReportErrorTypeEnumDataSetNotAvailable   CodatStandardReportingContractsReportErrorTypeEnum = "DataSetNotAvailable"
	CodatStandardReportingContractsReportErrorTypeEnumValidationError       CodatStandardReportingContractsReportErrorTypeEnum = "ValidationError"
)
