package shared

type CodatAssessDataContractsAccountCategoriesPatchSingleAccountCategoryModel struct {
	Confirmed *CodatAssessDataContractsAccountCategoriesConfirmedAccountCategoryModel `json:"confirmed,omitempty"`
}
