package shared

type CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnum string

const (
	CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnumDatesOutOfRange     CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnum = "DatesOutOfRange"
	CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnumDataNotSynced       CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnum = "DataNotSynced"
	CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnumDataSetNotSupported CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnum = "DataSetNotSupported"
	CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnumDataSyncFailed      CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnum = "DataSyncFailed"
	CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnumDataTypeNotEnabled  CodatAssessDataContractsFinancialsMetricsMetricDataSetErrorTypeEnum = "DataTypeNotEnabled"
)
