package shared

type CodatDataContractsDatasetsTaxRateStatusEnum string

const (
	CodatDataContractsDatasetsTaxRateStatusEnumUnknown  CodatDataContractsDatasetsTaxRateStatusEnum = "Unknown"
	CodatDataContractsDatasetsTaxRateStatusEnumActive   CodatDataContractsDatasetsTaxRateStatusEnum = "Active"
	CodatDataContractsDatasetsTaxRateStatusEnumArchived CodatDataContractsDatasetsTaxRateStatusEnum = "Archived"
)
