package shared

type CodatDataContractsDatasetsItemStatusEnum string

const (
	CodatDataContractsDatasetsItemStatusEnumUnknown  CodatDataContractsDatasetsItemStatusEnum = "Unknown"
	CodatDataContractsDatasetsItemStatusEnumActive   CodatDataContractsDatasetsItemStatusEnum = "Active"
	CodatDataContractsDatasetsItemStatusEnumArchived CodatDataContractsDatasetsItemStatusEnum = "Archived"
)
